:toc: left
:toclevels: 3     
:toc-title: Índice                                                

= Documentação dos Serviços Web do Servidor 

== Cadastrar jogador

Por meio deste serviço, um usuário cadastra-se para se participar do jogo.

A <<tbl:register_ok_request_fields,Tabela 1>> contém os campos que devem ser utilizados no corpo da requisição.

.Parâmetros do corpo da requisição.
[[tbl:register_ok_request_fields]]
include::target/snippets/registerOk/request-fields.adoc[]

Quando a requisição é exitosa, o servidor retorna um JSON cujos atributos do campo _content_ são mostrados na <<tbl:register_ok_response_fields,Tabela 2>>.

.Atributos do campo _content_ na resposta.
[[tbl:register_ok_response_fields]]
include::target/snippets/registerOk/response-fields.adoc[]

A seguir, são mostrados exemplos de uma requisição válida e de sua resposta.

.Requisição
include::target/snippets/registerOk/http-request.adoc[]

.Resposta
include::target/snippets/registerOk/http-response.adoc[]

Quando o jogador tenta se regitrar com um nome já utilizado, o servidor retorna a seguinte resposta: 

.Resposta
include::target/snippets/registerNameAlreadyUsed/http-response.adoc[]

Finalmente, no caso de um jogador tentar se conectar quando dois outros já o fizeram, a seguinte resposta
é retornada:

.Resposta
include::target/snippets/registerNoPlaceAvailable/http-response.adoc[]

== Obter informações iniciais do jogo

Após se cadastrar, por meio deste serviço o jogador obtém informações do jogo, como nomes e marcadores dos jogadores.
Tais informações não mudam no decorrer do jogo.

A <<tbl:game_info_ok_request_fields,Tabela 3>> contém os parâmetros que devem ser utilizados no corpo da requisição.

.Parâmetros do corpo da requisição.
[[tbl:game_info_ok_request_fields]]
include::target/snippets/gameInfoOk/request-parameters.adoc[]

Os atributos do campo _content_ da resposta do servidor são mostrados na <<tbl:game_info_ok_response_fields,Tabela 4>>.

.Atributos do campo _content_ na resposta.
[[tbl:game_info_ok_response_fields]]
include::target/snippets/gameInfoOk/response-fields.adoc[]

A seguir, são mostrados um exemplo de requisição válida e a resposta do servidor.

.Requisição
include::target/snippets/gameInfoOk/http-request.adoc[]

.Resposta
include::target/snippets/gameInfoOk/http-response.adoc[]

Caso o jogador forneça um identificador inválido, o servidor devolve o seguinte JSON:

.Resposta
include::target/snippets/gameInfoTokenIsInvalid/http-response.adoc[]

Finalmente, no caso de o identificador ser válido mas apenas um jogador ter se conectado,
o JSON a seguir é retornado pelo servidor:

.Resposta
include::target/snippets/gameInfoGameHasNotStartedYet/http-response.adoc[]

== Realizar jogada

Através deste serviço, o jogador pode realizar uma jogada.

A <<tbl:play_ok_request_fields,Tabela 5>> contém os campos que devem ser utilizados no corpo da requisição.

.Parâmetros do corpo da requisição.
[[tbl:play_ok_request_fields]]
include::target/snippets/playOk/request-fields.adoc[]

No caso deste método, o campo _content_ da resposta do servidor é sempre nulo, independentemente da requisição feita.

Mostram-se, a seguir, um exemplo de requisição válida e sua resposta correspondente:

.Requisição
include::target/snippets/playOk/http-request.adoc[]

.Resposta
include::target/snippets/playOk/http-response.adoc[]